name: Build sqlite-bundled with recover

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build
        run: ./gradlew :sqlite-bundled:assembleRelease

      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: sqlite-bundled-recover
          path: **/build/outputs/aar/*.aar